// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM-sZzxYHWx0jOchgcaAYaHU0UGApujV8',
    appId: '1:721535992428:web:11766046cb79a58d3c8e49',
    messagingSenderId: '721535992428',
    projectId: 'mynotes-armandoal-flutter',
    authDomain: 'mynotes-armandoal-flutter.firebaseapp.com',
    storageBucket: 'mynotes-armandoal-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Wd7GYpVGpnD_OSRzSa8yhEYkAspYdt0',
    appId: '1:721535992428:android:86b84323e72c90f23c8e49',
    messagingSenderId: '721535992428',
    projectId: 'mynotes-armandoal-flutter',
    storageBucket: 'mynotes-armandoal-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQPFC7B-Knvwfj5nutG0mVjCKOekdcAm8',
    appId: '1:721535992428:ios:b2160392a2ed036a3c8e49',
    messagingSenderId: '721535992428',
    projectId: 'mynotes-armandoal-flutter',
    storageBucket: 'mynotes-armandoal-flutter.appspot.com',
    iosClientId:
        '721535992428-vsvmvd75ppv0pivu5qsrlohulg4soia3.apps.googleusercontent.com',
    iosBundleId: 'com.tmh.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQPFC7B-Knvwfj5nutG0mVjCKOekdcAm8',
    appId: '1:721535992428:ios:b2160392a2ed036a3c8e49',
    messagingSenderId: '721535992428',
    projectId: 'mynotes-armandoal-flutter',
    storageBucket: 'mynotes-armandoal-flutter.appspot.com',
    iosClientId:
        '721535992428-vsvmvd75ppv0pivu5qsrlohulg4soia3.apps.googleusercontent.com',
    iosBundleId: 'com.tmh.mynotes',
  );
}
